export const KATANA_FACTORY_ABI = [
	{
		constant: false,
		inputs: [
			{ internal_type: '', name: '_treasury', type: 'address', indexed: false },
			{ internal_type: '', name: '_pairImplementation', type: 'address', indexed: false },
		],
		name: '',
		outputs: null,
		payable: false,
		stateMutability: 'nonpayable',
		type: 'constructor',
		anonymous: false,
	},
	{
		constant: false,
		inputs: [
			{ internal_type: '', name: '_oldAdmin', type: 'address', indexed: true },
			{ internal_type: '', name: '_newAdmin', type: 'address', indexed: true },
		],
		name: 'AdminChanged',
		outputs: null,
		payable: false,
		stateMutability: '',
		type: 'event',
		anonymous: false,
	},
	{
		constant: false,
		inputs: [{ internal_type: '', name: '_oldAdmin', type: 'address', indexed: true }],
		name: 'AdminRemoved',
		outputs: null,
		payable: false,
		stateMutability: '',
		type: 'event',
		anonymous: false,
	},
	{
		constant: false,
		inputs: [
			{ internal_type: '', name: '_token0', type: 'address', indexed: true },
			{ internal_type: '', name: '_token1', type: 'address', indexed: true },
			{ internal_type: '', name: '_pair', type: 'address', indexed: false },
			{ internal_type: '', name: '_allPairsLength', type: 'uint256', indexed: false },
		],
		name: 'PairCreated',
		outputs: null,
		payable: false,
		stateMutability: '',
		type: 'event',
		anonymous: false,
	},
	{
		constant: false,
		inputs: [
			{ internal_type: '', name: '_new', type: 'address', indexed: true },
			{ internal_type: '', name: '_old', type: 'address', indexed: true },
		],
		name: 'PairProxyUpdated',
		outputs: null,
		payable: false,
		stateMutability: '',
		type: 'event',
		anonymous: false,
	},
	{
		constant: true,
		inputs: [],
		name: 'INIT_CODE_PAIR_HASH',
		outputs: [{ internal_type: '', name: '', type: 'bytes32', indexed: false }],
		payable: false,
		stateMutability: 'view',
		type: 'function',
		anonymous: false,
	},
	{
		constant: true,
		inputs: [],
		name: 'admin',
		outputs: [{ internal_type: '', name: '', type: 'address', indexed: false }],
		payable: false,
		stateMutability: 'view',
		type: 'function',
		anonymous: false,
	},
	{
		constant: true,
		inputs: [{ internal_type: '', name: '', type: 'uint256', indexed: false }],
		name: 'allPairs',
		outputs: [{ internal_type: '', name: '', type: 'address', indexed: false }],
		payable: false,
		stateMutability: 'view',
		type: 'function',
		anonymous: false,
	},
	{
		constant: true,
		inputs: [],
		name: 'allPairsLength',
		outputs: [{ internal_type: '', name: '', type: 'uint256', indexed: false }],
		payable: false,
		stateMutability: 'view',
		type: 'function',
		anonymous: false,
	},
	{
		constant: true,
		inputs: [],
		name: 'allowedAll',
		outputs: [{ internal_type: '', name: '', type: 'bool', indexed: false }],
		payable: false,
		stateMutability: 'view',
		type: 'function',
		anonymous: false,
	},
	{
		constant: false,
		inputs: [{ internal_type: '', name: '_newAdmin', type: 'address', indexed: false }],
		name: 'changeAdmin',
		outputs: [],
		payable: false,
		stateMutability: 'nonpayable',
		type: 'function',
		anonymous: false,
	},
	{
		constant: false,
		inputs: [
			{ internal_type: '', name: '_tokenA', type: 'address', indexed: false },
			{ internal_type: '', name: '_tokenB', type: 'address', indexed: false },
		],
		name: 'createPair',
		outputs: [{ internal_type: '', name: '_pair', type: 'address', indexed: false }],
		payable: false,
		stateMutability: 'nonpayable',
		type: 'function',
		anonymous: false,
	},
	{
		constant: true,
		inputs: [
			{ internal_type: '', name: '', type: 'address', indexed: false },
			{ internal_type: '', name: '', type: 'address', indexed: false },
		],
		name: 'getPair',
		outputs: [{ internal_type: '', name: '', type: 'address', indexed: false }],
		payable: false,
		stateMutability: 'view',
		type: 'function',
		anonymous: false,
	},
	{
		constant: true,
		inputs: [],
		name: 'pairImplementation',
		outputs: [{ internal_type: '', name: '', type: 'address', indexed: false }],
		payable: false,
		stateMutability: 'view',
		type: 'function',
		anonymous: false,
	},
	{
		constant: false,
		inputs: [],
		name: 'removeAdmin',
		outputs: [],
		payable: false,
		stateMutability: 'nonpayable',
		type: 'function',
		anonymous: false,
	},
	{
		constant: false,
		inputs: [{ internal_type: '', name: '_allowedAll', type: 'bool', indexed: false }],
		name: 'setAllowedAll',
		outputs: [],
		payable: false,
		stateMutability: 'nonpayable',
		type: 'function',
		anonymous: false,
	},
	{
		constant: false,
		inputs: [{ internal_type: '', name: '_pairImplementation', type: 'address', indexed: false }],
		name: 'setPairImplementation',
		outputs: [],
		payable: false,
		stateMutability: 'nonpayable',
		type: 'function',
		anonymous: false,
	},
	{
		constant: false,
		inputs: [{ internal_type: '', name: '_treasury', type: 'address', indexed: false }],
		name: 'setTreasury',
		outputs: [],
		payable: false,
		stateMutability: 'nonpayable',
		type: 'function',
		anonymous: false,
	},
	{
		constant: true,
		inputs: [],
		name: 'treasury',
		outputs: [{ internal_type: '', name: '', type: 'address', indexed: false }],
		payable: false,
		stateMutability: 'view',
		type: 'function',
		anonymous: false,
	},
]
