export const USD_COIN = {
	name: 'USD Coin',
	address: '0x0b7007c13325c48911f73a2dad5fa5dcbf808adc',
	abi: [
		{
			anonymous: false,
			inputs: [],
			name: '',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'constructor',
		},
		{
			anonymous: false,
			inputs: [
				{
					indexed: true,
					internal_type: '',
					name: '_oldAdmin',
					type: 'address',
				},
				{
					indexed: true,
					internal_type: '',
					name: '_newAdmin',
					type: 'address',
				},
			],
			name: 'AdminChanged',
			outputs: [],
			payable: false,
			stateMutability: '',
			type: 'event',
		},
		{
			anonymous: false,
			inputs: [
				{
					indexed: true,
					internal_type: '',
					name: '_oldAdmin',
					type: 'address',
				},
			],
			name: 'AdminRemoved',
			outputs: [],
			payable: false,
			stateMutability: '',
			type: 'event',
		},
		{
			anonymous: false,
			inputs: [
				{
					indexed: true,
					internal_type: '',
					name: '_owner',
					type: 'address',
				},
				{
					indexed: true,
					internal_type: '',
					name: '_spender',
					type: 'address',
				},
				{
					indexed: false,
					internal_type: '',
					name: '_value',
					type: 'uint256',
				},
			],
			name: 'Approval',
			outputs: [],
			payable: false,
			stateMutability: '',
			type: 'event',
		},
		{
			anonymous: false,
			inputs: [
				{
					indexed: true,
					internal_type: '',
					name: '_minter',
					type: 'address',
				},
			],
			name: 'MinterAdded',
			outputs: [],
			payable: false,
			stateMutability: '',
			type: 'event',
		},
		{
			anonymous: false,
			inputs: [
				{
					indexed: true,
					internal_type: '',
					name: '_minter',
					type: 'address',
				},
			],
			name: 'MinterRemoved',
			outputs: [],
			payable: false,
			stateMutability: '',
			type: 'event',
		},
		{
			anonymous: false,
			inputs: [],
			name: 'Paused',
			outputs: [],
			payable: false,
			stateMutability: '',
			type: 'event',
		},
		{
			anonymous: false,
			inputs: [
				{
					indexed: true,
					internal_type: '',
					name: '_spender',
					type: 'address',
				},
			],
			name: 'SpenderUnwhitelisted',
			outputs: [],
			payable: false,
			stateMutability: '',
			type: 'event',
		},
		{
			anonymous: false,
			inputs: [
				{
					indexed: true,
					internal_type: '',
					name: '_spender',
					type: 'address',
				},
			],
			name: 'SpenderWhitelisted',
			outputs: [],
			payable: false,
			stateMutability: '',
			type: 'event',
		},
		{
			anonymous: false,
			inputs: [
				{
					indexed: true,
					internal_type: '',
					name: '_from',
					type: 'address',
				},
				{
					indexed: true,
					internal_type: '',
					name: '_to',
					type: 'address',
				},
				{
					indexed: false,
					internal_type: '',
					name: '_value',
					type: 'uint256',
				},
			],
			name: 'Transfer',
			outputs: [],
			payable: false,
			stateMutability: '',
			type: 'event',
		},
		{
			anonymous: false,
			inputs: [],
			name: 'Unpaused',
			outputs: [],
			payable: false,
			stateMutability: '',
			type: 'event',
		},
		{
			anonymous: false,
			inputs: [
				{
					indexed: false,
					internal_type: '',
					name: '_addedMinters',
					type: 'address[]',
				},
			],
			name: 'addMinters',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			anonymous: false,
			constant: true,
			inputs: [],
			name: 'admin',
			outputs: [
				{
					indexed: false,
					internal_type: '',
					name: '',
					type: 'address',
				},
			],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			anonymous: false,
			constant: true,
			inputs: [
				{
					indexed: false,
					internal_type: '',
					name: '_owner',
					type: 'address',
				},
				{
					indexed: false,
					internal_type: '',
					name: '_spender',
					type: 'address',
				},
			],
			name: 'allowance',
			outputs: [
				{
					indexed: false,
					internal_type: '',
					name: '_value',
					type: 'uint256',
				},
			],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			anonymous: false,
			inputs: [
				{
					indexed: false,
					internal_type: '',
					name: '_spender',
					type: 'address',
				},
				{
					indexed: false,
					internal_type: '',
					name: '_value',
					type: 'uint256',
				},
			],
			name: 'approve',
			outputs: [
				{
					indexed: false,
					internal_type: '',
					name: '_success',
					type: 'bool',
				},
			],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			anonymous: false,
			constant: true,
			inputs: [
				{
					indexed: false,
					internal_type: '',
					name: '',
					type: 'address',
				},
			],
			name: 'balanceOf',
			outputs: [
				{
					indexed: false,
					internal_type: '',
					name: '',
					type: 'uint256',
				},
			],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			anonymous: false,
			inputs: [
				{
					indexed: false,
					internal_type: '',
					name: '_value',
					type: 'uint256',
				},
			],
			name: 'burn',
			outputs: [
				{
					indexed: false,
					internal_type: '',
					name: '_success',
					type: 'bool',
				},
			],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			anonymous: false,
			inputs: [
				{
					indexed: false,
					internal_type: '',
					name: '_from',
					type: 'address',
				},
				{
					indexed: false,
					internal_type: '',
					name: '_value',
					type: 'uint256',
				},
			],
			name: 'burnFrom',
			outputs: [
				{
					indexed: false,
					internal_type: '',
					name: '_success',
					type: 'bool',
				},
			],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			anonymous: false,
			inputs: [
				{
					indexed: false,
					internal_type: '',
					name: '_newAdmin',
					type: 'address',
				},
			],
			name: 'changeAdmin',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			anonymous: false,
			constant: true,
			inputs: [],
			name: 'decimals',
			outputs: [
				{
					indexed: false,
					internal_type: '',
					name: '',
					type: 'uint8',
				},
			],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			anonymous: false,
			inputs: [],
			name: 'initialize',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			anonymous: false,
			constant: true,
			inputs: [
				{
					indexed: false,
					internal_type: '',
					name: '_addr',
					type: 'address',
				},
			],
			name: 'isMinter',
			outputs: [
				{
					indexed: false,
					internal_type: '',
					name: '',
					type: 'bool',
				},
			],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			anonymous: false,
			inputs: [
				{
					indexed: false,
					internal_type: '',
					name: '_to',
					type: 'address',
				},
				{
					indexed: false,
					internal_type: '',
					name: '_value',
					type: 'uint256',
				},
			],
			name: 'mint',
			outputs: [
				{
					indexed: false,
					internal_type: '',
					name: '_success',
					type: 'bool',
				},
			],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			anonymous: false,
			constant: true,
			inputs: [
				{
					indexed: false,
					internal_type: '',
					name: '',
					type: 'address',
				},
			],
			name: 'minter',
			outputs: [
				{
					indexed: false,
					internal_type: '',
					name: '',
					type: 'bool',
				},
			],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			anonymous: false,
			constant: true,
			inputs: [
				{
					indexed: false,
					internal_type: '',
					name: '',
					type: 'uint256',
				},
			],
			name: 'minters',
			outputs: [
				{
					indexed: false,
					internal_type: '',
					name: '',
					type: 'address',
				},
			],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			anonymous: false,
			constant: true,
			inputs: [],
			name: 'name',
			outputs: [
				{
					indexed: false,
					internal_type: '',
					name: '',
					type: 'string',
				},
			],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			anonymous: false,
			inputs: [],
			name: 'pause',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			anonymous: false,
			constant: true,
			inputs: [],
			name: 'paused',
			outputs: [
				{
					indexed: false,
					internal_type: '',
					name: '',
					type: 'bool',
				},
			],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			anonymous: false,
			inputs: [],
			name: 'removeAdmin',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			anonymous: false,
			inputs: [
				{
					indexed: false,
					internal_type: '',
					name: '_removedMinters',
					type: 'address[]',
				},
			],
			name: 'removeMinters',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			anonymous: false,
			constant: true,
			inputs: [],
			name: 'symbol',
			outputs: [
				{
					indexed: false,
					internal_type: '',
					name: '',
					type: 'string',
				},
			],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			anonymous: false,
			constant: true,
			inputs: [],
			name: 'totalSupply',
			outputs: [
				{
					indexed: false,
					internal_type: '',
					name: '',
					type: 'uint256',
				},
			],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
		{
			anonymous: false,
			inputs: [
				{
					indexed: false,
					internal_type: '',
					name: '_to',
					type: 'address',
				},
				{
					indexed: false,
					internal_type: '',
					name: '_value',
					type: 'uint256',
				},
			],
			name: 'transfer',
			outputs: [
				{
					indexed: false,
					internal_type: '',
					name: '_success',
					type: 'bool',
				},
			],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			anonymous: false,
			inputs: [
				{
					indexed: false,
					internal_type: '',
					name: '_from',
					type: 'address',
				},
				{
					indexed: false,
					internal_type: '',
					name: '_to',
					type: 'address',
				},
				{
					indexed: false,
					internal_type: '',
					name: '_value',
					type: 'uint256',
				},
			],
			name: 'transferFrom',
			outputs: [
				{
					indexed: false,
					internal_type: '',
					name: '_success',
					type: 'bool',
				},
			],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			anonymous: false,
			inputs: [],
			name: 'unpause',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			anonymous: false,
			inputs: [
				{
					indexed: false,
					internal_type: '',
					name: '_spender',
					type: 'address',
				},
			],
			name: 'unwhitelist',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			anonymous: false,
			inputs: [
				{
					indexed: false,
					internal_type: '',
					name: '_spender',
					type: 'address',
				},
			],
			name: 'whitelist',
			outputs: [],
			payable: false,
			stateMutability: 'nonpayable',
			type: 'function',
		},
		{
			anonymous: false,
			constant: true,
			inputs: [
				{
					indexed: false,
					internal_type: '',
					name: '',
					type: 'address',
				},
			],
			name: 'whitelisted',
			outputs: [
				{
					indexed: false,
					internal_type: '',
					name: '',
					type: 'bool',
				},
			],
			payable: false,
			stateMutability: 'view',
			type: 'function',
		},
	],
}
